include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_returning_null_for_void: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    deprecated_consistency: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_relative_imports: true
    sized_box_for_whitespace: true
    use_super_parameters: true
    valid_regexps: true

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    invalid_annotation_target: ignore

# Ignore specific files or patterns
exclude:
  - lib/generated_plugin_registrant.dart
  - '**/*.g.dart'
  - '**/*.freezed.dart'
  - test/generated_migrations/**
